name: Build LaTeX document
on:
  push:
    branches: [ main ]
jobs:
  build_and_publish_tex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: src/main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Gather build artifacts
        run: |
          mkdir build
          mv example-*.pdf build/
          mv example-*.png build/
          cp -r README.md .github/_config.yml build/
      - name: Publish to GitHub pages
        if: success() && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
